---
- name: Allow ovirt_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ ovirt_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Deploy password file
  copy:
    content: "{{ ovirt_exporter_password }}"
    dest: "{{ ovirt_exporter_password_file }}"
    owner: "{{ ovirt_exporter_system_user }}"
    group: "{{ ovirt_exporter_system_group }}"
    mode: '0600'
  when: ovirt_exporter_password_file is defined
