---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ovirt_exporter_dependencies }}"

- name: Create the ovirt_exporter group
  group:
    name: "{{ ovirt_exporter_system_group }}"
    state: present
    system: true

- name: Create the ovirt_exporter user
  user:
    name: "{{ ovirt_exporter_system_user }}"
    groups: "{{ ovirt_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

# - name: Download ovirt_exporter binary to local folder
#   become: false
#   get_url:
#     url: "https://github.com/czerwonk/ovirt_exporter/releases/download/v{{ ovirt_exporter_version }}/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
#     dest: "/tmp/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
# #    checksum: "sha256:{{ ovirt_exporter_checksum }}"
#   register: _download_binary
#   until: _download_binary is succeeded
#   retries: 5
#   delay: 2
#   delegate_to: localhost
#   check_mode: false

# - name: Unpack ovirt_exporter binary
#   become: false
#   unarchive:
#     src: "/tmp/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
#     dest: "/tmp"
#     creates: "/tmp/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] }}/ovirt_exporter"
#   delegate_to: localhost
#   check_mode: false

- name: Unpack ovirt_exporter binary
  become: false
  unarchive:
    src: "files/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] }}/ovirt_exporter"
  delegate_to: localhost
  check_mode: false

- name: Propagate ovirt_exporter binaries
  copy:
    src: "/tmp/ovirt_exporter-{{ ovirt_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] }}/ovirt_exporter"
    dest: "/usr/local/bin/ovirt_exporter"
    mode: 0750
    owner: "{{ ovirt_exporter_system_user }}"
    group: "{{ ovirt_exporter_system_group }}"
    setype: bin_t
  notify: restart ovirt_exporter
  when: not ansible_check_mode

- name: Copy the ovirt_exporter systemd service file
  template:
    src: ovirt_exporter.service.j2
    dest: /etc/systemd/system/ovirt_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart ovirt_exporter
